/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppStrengthRouteImport } from './routes/app.strength'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRunningRouteImport } from './routes/app.running'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppMobilityRouteImport } from './routes/app.mobility'
import { Route as AppCoachRouteImport } from './routes/app.coach'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AuthStravaCallbackRouteImport } from './routes/auth.strava.callback'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStrengthRoute = AppStrengthRouteImport.update({
  id: '/strength',
  path: '/strength',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRunningRoute = AppRunningRouteImport.update({
  id: '/running',
  path: '/running',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMobilityRoute = AppMobilityRouteImport.update({
  id: '/mobility',
  path: '/mobility',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AuthStravaCallbackRoute = AuthStravaCallbackRouteImport.update({
  id: '/auth/strava/callback',
  path: '/auth/strava/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/coach': typeof AppCoachRoute
  '/app/mobility': typeof AppMobilityRoute
  '/app/profile': typeof AppProfileRoute
  '/app/running': typeof AppRunningRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/strength': typeof AppStrengthRoute
  '/app/': typeof AppIndexRoute
  '/auth/strava/callback': typeof AuthStravaCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/coach': typeof AppCoachRoute
  '/app/mobility': typeof AppMobilityRoute
  '/app/profile': typeof AppProfileRoute
  '/app/running': typeof AppRunningRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/strength': typeof AppStrengthRoute
  '/app': typeof AppIndexRoute
  '/auth/strava/callback': typeof AuthStravaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/coach': typeof AppCoachRoute
  '/app/mobility': typeof AppMobilityRoute
  '/app/profile': typeof AppProfileRoute
  '/app/running': typeof AppRunningRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/strength': typeof AppStrengthRoute
  '/app/': typeof AppIndexRoute
  '/auth/strava/callback': typeof AuthStravaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/app/calendar'
    | '/app/coach'
    | '/app/mobility'
    | '/app/profile'
    | '/app/running'
    | '/app/settings'
    | '/app/strength'
    | '/app/'
    | '/auth/strava/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/app/calendar'
    | '/app/coach'
    | '/app/mobility'
    | '/app/profile'
    | '/app/running'
    | '/app/settings'
    | '/app/strength'
    | '/app'
    | '/auth/strava/callback'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/app/calendar'
    | '/app/coach'
    | '/app/mobility'
    | '/app/profile'
    | '/app/running'
    | '/app/settings'
    | '/app/strength'
    | '/app/'
    | '/auth/strava/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  AuthStravaCallbackRoute: typeof AuthStravaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/strength': {
      id: '/app/strength'
      path: '/strength'
      fullPath: '/app/strength'
      preLoaderRoute: typeof AppStrengthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/running': {
      id: '/app/running'
      path: '/running'
      fullPath: '/app/running'
      preLoaderRoute: typeof AppRunningRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mobility': {
      id: '/app/mobility'
      path: '/mobility'
      fullPath: '/app/mobility'
      preLoaderRoute: typeof AppMobilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coach': {
      id: '/app/coach'
      path: '/coach'
      fullPath: '/app/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/strava/callback': {
      id: '/auth/strava/callback'
      path: '/auth/strava/callback'
      fullPath: '/auth/strava/callback'
      preLoaderRoute: typeof AuthStravaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppCoachRoute: typeof AppCoachRoute
  AppMobilityRoute: typeof AppMobilityRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRunningRoute: typeof AppRunningRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStrengthRoute: typeof AppStrengthRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppCoachRoute: AppCoachRoute,
  AppMobilityRoute: AppMobilityRoute,
  AppProfileRoute: AppProfileRoute,
  AppRunningRoute: AppRunningRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStrengthRoute: AppStrengthRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  AuthStravaCallbackRoute: AuthStravaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
