// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Log de aviso mas NÃO lança erro — evita travar o React antes de montar
  console.warn(
    '[Supabase] Variáveis de ambiente ausentes: VITE_SUPABASE_URL e/ou VITE_SUPABASE_PUBLISHABLE_KEY.\n' +
    'Crie um arquivo .env na raiz do projeto com essas variáveis.\n' +
    'Encontre os valores em: https://supabase.com/dashboard → seu projeto → Settings → API'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(
  SUPABASE_URL ?? 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY ?? 'placeholder-key',
  {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);