// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmpmtexkoxprbswfapjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtcG10ZXhrb3hwcmJzd2ZhcGpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkxMTI2MTEsImV4cCI6MjA5NDY4ODYxMX0.h-L0g2ey6PA0qXK0EKjFHL0rMpUygn7HH6xYBFV6vuo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);